version: "3.8"
services:
  jihye:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: jihye-bot:dev
    env_file:
      - .env
    volumes:
      - ./:/app
    restart: unless-stopped
